language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kylecribbs
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: kylecribbs/pyarcher
    python: 3.7
  password=KFCrcs1831!!:
    secure: DClRe4Oxzv+dELndxu4d4Uv065cE25XVd5PFn4EKFMQ0Xwb6X148OHqAHcG0e7fMBVRFRwWl4ouSwvT5bM/tkMfC0sd0roIs5Z7e3ECXD9nuhmVHpOL97s1vDSbLXejP/zW7nu9v0b7PfrayQHtkNyrqLeniUsZyVfn/ju2lJ8Uoj8dEWhVXJCWUu8JEUAip25YyeE0c58J7e8k2V7MjZFXE9oyZhIDHNuIvQddnq+msBHsEsYdxnD+7u7JVRpWrPZZ/Hruz0sfrh0JoG1tu70V5YZ8LLGD2ail2i+JZ03eBiFA4n6bX+zQhD3Ca4HDy6TuW2KddJVW3nI8MRuGidB7DQNCkMMg6o4oa0nl5G71lsAwcKJxukcHG4Gi58uBfcAfp4hbMw1bn7Mq1aEbWpvNDOKKDEEmAefnrra2jZafBd47dtl7j0AtwHlhNjiDALPxsDWSzI/SZpAXmwi3wgAHIEj/iDx2Kin+0MS//nvSHH/hJj0Jq1D2VXkoVspp27ofMYnq9IVxvqgX/hhDjx4XiR4ta3qj1CzdjU2XvsoM8eJGIqGIKlnsJLKifvYEP2eRhd4GZ1xBHviGAbbFkm3EKveGe2Ikdx5qn6xFke2JjDoL4ceFO4BaphzRq5SCybhxwxcRWDySMAJ2T6D4uOhSiBFks5R7eKiJU5eOCNEM=
